function_body_length:
  warning: 120
  error: 300

type_body_length:
  warning: 400
  error: 1000

file_length:
  warning: 400
  error: 1000

# rule identifiers to exclude from running
disabled_rules:
  - identifier_name
  - line_length
  - nesting
  - todo
  - empty_parentheses_with_trailing_closure

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - Tests
  - Docs
